#!/bin/bash

# --------------------------------------------------
# Configuration variables
# --------------------------------------------------

# GitLab
UNICORN_WORKERS="2"

# --------------------------------------------------
# Config PostgreSQL
# --------------------------------------------------

# Start the service to make database reachable
/etc/init.d/postgresql start

# Create a user for GitLab
sudo -u postgres psql --command "CREATE USER git CREATEDB;"
sudo -u postgres psql --command "CREATE DATABASE gitlabhq_production OWNER git;"

# --------------------------------------------------
# Config Redis
# --------------------------------------------------

# Configure redis to use sockets
cp /etc/redis/redis.conf /etc/redis/redis.conf.orig

# Disable Redis listening on TCP by setting 'port' to 0
#sed 's/^port .*/port 0/' /etc/redis/redis.conf.orig | tee /etc/redis/redis.conf
sed 's/^port .*/port 0/' /etc/redis/redis.conf.orig > /etc/redis/redis.conf

# Enable Redis socket for default Debian / Ubuntu path
#echo 'unixsocket /var/run/redis/redis.sock' | tee -a /etc/redis/redis.conf
echo 'unixsocket /var/run/redis/redis.sock' >> /etc/redis/redis.conf

# Activate the changes to redis.conf
#service redis-server restart
service redis-server start

# Add git to the redis group
usermod -aG redis git

# --------------------------------------------------
# Config GitLab
# --------------------------------------------------

# Go to GitLab installation folder
cd /home/git/gitlab

# Copy the example GitLab config
#sudo -u git -H cp config/gitlab.yml.example config/gitlab.yml

# Update GitLab config file, follow the directions at top of file
#sudo -u git -H editor config/gitlab.yml
sudo -u git -H sed 's,bin_path: /usr/bin/git,bin_path: /usr/local/bin/git,' config/gitlab.yml.example > config/gitlab.yml

# Make sure GitLab can write to the log/ and tmp/ directories
sudo chown -R git log/
sudo chown -R git tmp/
sudo chmod -R u+rwX log/
sudo chmod -R u+rwX tmp/

# Create directory for satellites
sudo -u git -H mkdir /home/git/gitlab-satellites
sudo chmod u+rwx,g=rx,o-rwx /home/git/gitlab-satellites

# Make sure GitLab can write to the tmp/pids/ and tmp/sockets/ directories
sudo chmod -R u+rwX tmp/pids/
sudo chmod -R u+rwX tmp/sockets/

# Make sure GitLab can write to the public/uploads/ directory
sudo chmod -R u+rwX  public/uploads

# Copy the example Unicorn config
#sudo -u git -H cp config/unicorn.rb.example config/unicorn.rb

# Enable cluster mode if you expect to have a high load instance
# Ex. change amount of workers to 3 for 2GB RAM server
# Set the number of workers to at least the number of cores
sudo -u git -H sed "s/worker_processes 2/worker_processes ${UNICORN_WORKERS}/" config/unicorn.rb.example > config/unicorn.rb

# Copy the example Rack attack config
sudo -u git -H cp config/initializers/rack_attack.rb.example config/initializers/rack_attack.rb

# Configure Git global settings for git user, useful when editing via web
# Edit user.email according to what is set in gitlab.yml
sudo -u git -H git config --global user.name "GitLab"
sudo -u git -H git config --global user.email "example@example.com"
sudo -u git -H git config --global core.autocrlf input

# Configure Redis connection settings
sudo -u git -H cp config/resque.yml.example config/resque.yml

# Change the Redis socket path if you are not using the default Debian / Ubuntu configuration
#sudo -u git -H editor config/resque.yml

# PostgreSQL only:
sudo -u git cp config/database.yml.postgresql config/database.yml

# PostgreSQL and MySQL:
# Make config/database.yml readable to git only
sudo -u git -H chmod o-rwx config/database.yml

# --------------------------------------------------
# Install Gems
# --------------------------------------------------

# For PostgreSQL (note, the option says "without ... mysql")
sudo -u git -H bundle install --deployment --without development test mysql aws

# --------------------------------------------------
# Install GitLab Shell
# --------------------------------------------------

# Run the installation task for gitlab-shell (replace `REDIS_URL` if needed):
sudo -u git -H bundle exec rake gitlab:shell:install[v2.0.1] REDIS_URL=unix:/var/run/redis/redis.sock RAILS_ENV=production

# By default, the gitlab-shell config is generated from your main GitLab config.
# You can review (and modify) the gitlab-shell config as follows:
#sudo -u git -H editor /home/git/gitlab-shell/config.yml

# --------------------------------------------------
# Initialize Database and Activate Advanced Features
# --------------------------------------------------

sudo -u git -H echo yes | bundle exec rake gitlab:setup RAILS_ENV=production

# --------------------------------------------------
# IOnstall Init Script
# --------------------------------------------------

cp lib/support/init.d/gitlab /etc/init.d/gitlab

# --------------------------------------------------
# Setup Logrotate
# --------------------------------------------------

cp lib/support/logrotate/gitlab /etc/logrotate.d/gitlab

# --------------------------------------------------
# Compile Assets
# --------------------------------------------------

sudo -u git -H bundle exec rake assets:precompile RAILS_ENV=production

# --------------------------------------------------
# Setup Nginx
# --------------------------------------------------

# Copy the example site config:
cp lib/support/nginx/gitlab /etc/nginx/sites-available/gitlab
ln -s /etc/nginx/sites-available/gitlab /etc/nginx/sites-enabled/gitlab

# Change YOUR_SERVER_FQDN to the fully-qualified
# domain name of your host serving GitLab.
#sudo editor /etc/nginx/sites-available/gitlab



