#!/bin/bash

RUBY_VERSION=2.1.3

mkdir /tmp/ruby
cd /tmp/ruby
curl -L --progress ftp://ftp.ruby-lang.org/pub/ruby/2.1/ruby-${RUBY_VERSION}.tar.gz | tar xz
cd ruby-${RUBY_VERSION}
./configure --disable-install-rdoc
make
make install
gem install bundler --no-ri --no-rdoc

